apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.store.name }}
  namespace: {{ .Values.ns }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.network.host }}
      http:
        paths:
          - path: {{ .Values.network.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.store.name }}
                port:
                  number: {{ .Values.network.port }}
