---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: getting-started
  name: getting-started
  namespace: {{ .Values.ns }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: getting-started
---
