apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "store.name" . }}-ingress
  namespace: {{ .Values.ns }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix

            backend:
              service:
                name: {{ template "store.name" . }}
                port:
                  number: {{ .Values.service.port }}
